# Site settings
author: Batsaikhan Ulambayar
title: Sinatra Application Project
header-img: img/home-bg.png
email: u.batsaikhan@gmail.com
copyright_name: Batsaikhan Ulambayar
description: > # this means to ignore newlines until "baseurl:"
  Final Project for Sinatra 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ubatsaikhan
github_username:  batsaikhan84

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
